### ISSUE TITLE
自动隐藏空字段？

### ISSUE THREAD

**Issue by HibernalGlow** [loonghfut/siyuan-database-display#1]

**Comment by loonghfut** [comment]
是的，因为这个插件只显示数据库中的属性的值，不显示属性，故空字段就自动隐藏了（不隐藏留一个空出来不好看）

**Comment by HibernalGlow** [comment]
![image](https://github.com/user-attachments/assets/8965805f-0fdf-41cb-b52e-4757d0bbc430)
不是我的意思是 有些为零的自动 还有日期啥的没隐藏

**Comment by loonghfut** [comment]
我还没遇到过这个情况，这个文档的数据库属性是什么

**Comment by HibernalGlow** [comment]
![image](https://github.com/user-attachments/assets/fa40c7ba-8529-43c4-ad4a-70d5090a81af)
汇总 和一些模板

**Comment by loonghfut** [comment]
模板列和汇总列，我记得我当时写代码的时候是没包括的，应该不会显示才对
看来是bug，感谢反馈，后天考完试再看看，最迟这周修好

**Comment by HibernalGlow** [comment]
这个用自定义显示也能解决

**Comment by loonghfut** [comment]
> 这个用自定义显示也能解决

你是指自定义显示数据库中的属性？

**Comment by loonghfut** [comment]
> > > 这个用自定义显示也能解决
> > 
> > 你是指自定义显示数据库中的属性？
> 
> 对啊 与其隐藏不如让用的人自己选

之后是有这计划的，既然你提了，那下个版本就实现。（优先参考issue中的建议）

本来是想着想弄一个开箱即用的插件，后面在加自定义的功能（包括自定义样式，显示的内容，显示的范围等），如果一开始搞，工作量有点大，且用得还麻烦（要配置一堆东西）。

**Comment by loonghfut** [comment]
> ![image](https://private-user-images.githubusercontent.com/154863885/391593710-fa40c7ba-8529-43c4-ad4a-70d5090a81af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMTkyNDYsIm5iZiI6MTczMzMxODk0NiwicGF0aCI6Ii8xNTQ4NjM4ODUvMzkxNTkzNzEwLWZhNDBjN2JhLTg1MjktNDNjNC1hZDRhLTcwZDUwOTBhODFhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxMzI5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWQ1NDAxZWUyYmFjNmE3NzVjYjc5OGU2NjY1NDRmMTVkYzQ3OGZlYmI5Yjc5NmQ3ZGIwYWNmMWMxOTJiNzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ft5LbmDqa7CflzwaQe5KFHNoJ-nS3MZ8hrZzflqlc6k) 汇总 和一些模板

我目前无法复现你这种情况（不会显示模板和汇总的字段）。若之后更新插件版本后还出现改问题，若方便，希望你将你的数据库的相关字段去敏后发给我zhoustevelong@outlook.com

**Comment by HibernalGlow** [comment]
正常显示了佬 期待普通块的显示 因为我也快期末考试了…… 正好看数据库收集的重点

**Comment by loonghfut** [comment]
> 正常显示了佬 期待普通块的显示 因为我也快期末考试了…… 正好看数据库收集的重点

段落块显示已实现，至于其他类型的块实现起来较为复杂，且我也没有太大需求，后续尝试支持列表块显示，不打算实现所有块的显示（太复杂了，要考虑的情况太多了）

**Comment by HibernalGlow** [comment]
> > 正常显示了佬 期待普通块的显示 因为我也快期末考试了…… 正好看数据库收集的重点
> 
> 段落块显示已实现，至于其他类型的块实现起来较为复杂，且我也没有太大需求，后续尝试支持列表块显示，不打算实现所有块的显示（太复杂了，要考虑的情况太多了）

可以加上标题块吗 这个我用的最多

**Comment by loonghfut** [comment]
OK.还有什么块你比较常用，我优先适配
（目前似乎手机端用不了）

**Comment by HibernalGlow** [comment]
> OK.还有什么块你比较常用，我优先适配
> （目前似乎手机端用不了）

加个列表和引述基本就全覆盖了

**Comment by loonghfut** [comment]
换了一种思路，理论上支持所有块，未做全面测试，希望能帮忙测试下0.3.0版本

**Comment by HibernalGlow** [comment]
> 换了一种思路，理论上支持所有块，未做全面测试，希望能帮忙测试下0.3.0版本

自定义字段显示后 右上标签大概率不显示 默认全词条也又是不显示

**Comment by loonghfut** [comment]
刷新一下，或者换几个笔记页看看

**Comment by HibernalGlow** [comment]
> 刷新一下，或者换几个笔记页看看

试过了 时有时无的

**Comment by HibernalGlow** [comment]
> 刷新一下，或者换几个笔记页看看

试过了 时有时无的

**Comment by loonghfut** [comment]
你的思源是什么平台的

**Comment by HibernalGlow** [comment]
> 你的思源是什么平台的

win11 23h2

**Comment by loonghfut** [comment]
（不应该啊，我也用的win11，但显示不出来的情况几乎没遇到，难道我单篇笔记太少了？，对了，笔记分屏会导致部分显示失效【已知问题】）显示不出来的时候，打开日志看看有没有什么报错

**Comment by loonghfut** [comment]
刚打开思源的显示的笔记不会显示（已知问题）但切换一下笔记就可以解决了，（因为只监听了切换笔记的事件，后面版本我改进改进）

那目前的显示位置什么的，有没有问题

**Comment by HibernalGlow** [comment]
> （不应该啊，我也用的win11，但显示不出来的情况几乎没遇到，难道我单篇笔记太少了？，对了，笔记分屏会导致部分显示失效【已知问题】）显示不出来的时候，打开日志看看有没有什么报错

我都是分屏用的 怪不得

**Comment by loonghfut** [comment]
>  我都是分屏用的 怪不得 

了解😂，我看看能不能优化一下

**Comment by loonghfut** [comment]
v0.3.5优化了一下应该不显示的概率会低很多（包括分屏的情况）
