### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by gradypark86** [loonghfut/siyuan-database-display#3]
感谢开发插件，使用过程中遇到了两个小问题：

1. 鼠标悬停在数据库名称处（即图中红框区域）触发浮窗时，插件显示内容即会消失，刷新页面后恢复正常。
<img width="1086" alt="image" src="https://github.com/user-attachments/assets/88d4c279-4672-4847-971b-09a96430c08e" />

2. 当前不显示数据库中暂无内容的字段。数据库中有些字段内容（例如日期等）当前无法确定保持为空，待确定后填写，但由于插件不会展示无数据的字段，只能返回数据库进行补全。如图所示，该条目与上图为同一数据库，由于尚未在数据库中填写日期，插件处没有显示，即无法直接在此处填写缺失字段。不知能否保留显示无内容的字段？
<img width="301" alt="image" src="https://github.com/user-attachments/assets/1d89c53c-9996-4162-9c19-deac512191dd" />

非常感谢。

**Comment by loonghfut** [comment]
1.感谢反馈，由于我不怎么用悬浮预览，故没做相关优化，后面有时间我试试能不能解决

2.如果为空的要显示，那应该显示什么呢

还有
> 由于尚未在数据库中填写日期，插件处没有显示，即无法直接在此处填写缺失字段

这句话我没太明白，在此处是指什么？

**Comment by loonghfut** [comment]
我，我突然明白了，你反馈错了，你说的问题是另一个插件的（我的插件只负责右上角的显示）

**Comment by gradypark86** [comment]
啊实在抱歉，发现确实反馈错插件了，打扰了🌝
